### ISSUE TITLE
Is NETSGPClient similar?

### ISSUE THREAD

**Issue by wwk-github** [mcmaier/hoymiles-nrf-comm_demo#2]
Hello.
It would be great to have an own communication with HM micro-inverters without the need for DTU device.

Is https://github.com/atc1441/NETSGPClient a project that could help?
What other help would be needed to make this project go forward?

**Comment by mcmaier** [comment]
Hello,

any help to push this project is appreciated. The main discussion (in German) happens on mikrocontroller.net
Unfortunately, someone already tested NETSGP without success. It seems, the Hoymiles inverters don't use this protocol:
https://www.mikrocontroller.net/topic/525778#6930091

Currently, a detailed analysis of the behavior of the wireless interface is ongoing - since it is not clear by now, in which order the channels are used and where the main communication is ongoing.
Another important point to evaluate is, if there needs to be an initial setup with the inverter to announce the DTU serial number.
